# Generated by Django 4.1.7 on 2023-02-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catogory',
            new_name='category',
        ),
    ]
